
# 需要 Multiverse-Core 插件作为前置插件,支持自己添加多个需要刷新的世界
自动刷新世界:
  # 世界名
  world_resource:

    # day,1 代表每天刷新一次
    # day,3 代表每 3 天刷新一次
    # week,7 代表每周日刷新一次
    # week,1 代表每周一刷新一次
    # month,1 代表每月 1 日刷新一次
    日期设置: "month,1"

    # 代表刷新的时间
    时间设置: "20:00"

    # 会自动设置刷新日期用来判断是否需要刷新, 你也可以手动设置刷新日期, 格式为 年,月,日,小时,分钟
    触发时间: "-1"

    # 是否更换种子
    更换种子: true

    # 自动设置刷新世界后的游戏规则
    游戏规则设置:
      # 开启死亡不掉落
      - 'keepInventory,true'
      # 不显示死亡界面直接重生
      - 'doImmediateRespawn,true'

  # 需要刷新的第二个世界
  world_example:

    日期设置: "month,1"
    时间设置: "20:00"
    触发时间: "-1"
    更换种子: true
    游戏规则设置:
      - 'keepInventory,true'
      - 'doImmediateRespawn,true'

自动删除文件:

  日志文件:
    日期设置: "day,1"
    时间设置: "20:00"
    刷新时间: "-1"
    文件路径:
      - 'logs'
      - 'crash-reports'