# 自动刷新世界的功能
自动刷新世界:
  # 在这里填写需要自动刷新的世界名, world_resource 就是当前所需刷新的世界名
  # papi 倒计时变量示例: %AutoResetWorld_countdown_自动刷新世界-world_resource%
  world_resource:

    # second:30 代表每 30 秒刷新一次
    # minute:10 代表每 10 分钟刷新一次
    # hour:3 代表每 3 小时刷新一次

    # date:10-01, 07:56:00 代表每年的 10 月 1 日 7:56 刷新一次

    # day:1, 20:00:00 代表每天 20:00:00 刷新一次
    # day:14, 00:00:00 代表每 14 天的 00:00:00 刷新一次
    # week:4, 23:59:59 代表每周 4 的 23:59:59 刷新一次
    # week:1, 06:00:00 代表每周 1 的 06:00:00 刷新一次
    # month:15, 12:34:45 代表每月 15 日的 12:34:45 刷新一次
    # year:233, 00:00:00 代表每年的第 233 天的 00:00:00 刷新一次

    时间设置: "month:1, 20:00:00"
    # 用于插件内部记录下一次刷新世界的时间, 当时间到达的指定时间后会自动刷新, 插件会自动设置, 无需手动设置
    # 支持手动设置到期时间, 例如 2050-09-13, 07:12:15 为 2050 年 9 月 13 日, 上午 7 点 12 分 15 秒
    到期时间: ""

    # 是否更换地图种子
    更换种子: true

    # 刷新后自动执行指令
    刷新执行指令:
      # 开启死亡不掉落
      - 'mvgamerule keepInventory true %world%'
      # 不显示死亡界面直接重生
      - 'mvgamerule doImmediateRespawn true %world%'
      # 如果你的服务器无区块占用世界会自动卸载(一般常见于 mod 服)
      # 可以使用下面的指令保持重生点区块加载, 去掉 # 符号开启即可
      #- 'mvm set keepspawninmemory true %world%'

  # 自动刷新 world_test 世界, 支持添加更多世界, 像这样复制在下面添加即可
  world_test:
    时间设置: "week:7, 10:00:00"
    更换种子: true
    刷新执行指令:
      - 'mvgamerule keepInventory true %world%'
      - 'mvgamerule doImmediateRespawn true %world%'
      -
  # 自动刷新 资源 世界, 支持添加更多世界, 像这样复制在下面添加即可
  资源:
    时间设置: "week:7, 10:00:00"
    更换种子: true
    刷新执行指令:
      - 'mvgamerule keepInventory true %world%'
      - 'mvgamerule doImmediateRespawn true %world%'
# 定时自动执行任务的功能
自动执行任务:
  coi数据清理:
    # 每天 03:30:00 执行 co i purge t:7d 指令
    时间设置: "day:1, 03:30:00"
    执行任务:
      - 'console: co l purge t:7d'
  # papi 倒计时变量示例: %AutoResetWorld_countdown_自动执行任务-自动重启%
  自动重启:
    # 每天 04:00:00 执行 restart 指令重启服务器
    时间设置: "day:1, 04:00:00"
    执行任务:
      - 'console: restart'
  自动公告:
    # 每分钟自动公告
    时间设置: "minute:1"
    执行任务:
      - 'broadcast: 资源世界每日刷新, 请不要在资源时间建家哦'
# 自动删除文件功能
自动删除文件:
  # 支持添加更多删除方案和删除路径
  # papi 倒计时变量示例: %AutoResetWorld_countdown_自动删除文件-日志文件%
  日志文件:
    # 每天清理一次日志文件
    时间设置: "day:1, 00:00:00"
    # 保留 7 天内的日志文件
    保留天数: 7
    文件路径:
      - 'logs'
      - 'crash-reports'