# 自动刷新世界的功能
自动刷新世界:
  # 在这里填写需要自动刷新的世界名, world_resource 就是当前所需刷新的世界名
  world_resource:

    # day,1 代表每天刷新一次
    # day,3 代表每 3 天刷新一次
    # week,7 代表每周日刷新一次
    # week,1 代表每周一刷新一次
    # month,1 代表每月 1 日刷新一次
    # month,15 代表每月 15 日刷新一次
    日期设置: "month,1"

    # 代表刷新的时间, 结合上面那条就是每月 1 日晚上 8 点刷新
    # 从 0:00 到 23:59
    时间设置: "20:00"

    # 用于插件内部记录下一次刷新世界的时间, 当时间到达的时间后会自动刷新
    # 插件会自动设置, 无需手动设置, 手动设置下一次刷新时间也是支持的, 格式为 年,月,日,小时,分钟
    触发时间: "-1"

    # 是否更换地图种子
    更换种子: true

    # 刷新后自动执行指令
    刷新执行指令:
      # 开启死亡不掉落
      - 'mvgamerule keepInventory true %world%'
      # 不显示死亡界面直接重生
      - 'mvgamerule doImmediateRespawn true %world%'
      # 如果你的服务器无区块占用世界会自动卸载(一般常见于 mod 服)
      # 可以使用下面的指令保持重生点区块加载, 去掉 # 符号开启即可
      #- 'mvm set keepspawninmemory true %world%'

  # 支持添加更多世界, 复制上面的世界配置文件后修改世界名即可

# 自动删除文件功能
自动删除文件:
  # 支持添加更多删除方案和删除路径
  日志文件:
    # 每天清理一次日志文件
    日期设置: "day,1"
    时间设置: "20:00"
    # 保留 7 天内的日志文件
    保留天数: 7
    触发时间: "-1"
    文件路径:
      - 'logs'
      - 'crash-reports'
