name: AutoRespawnWorld
main: com.entiv.${name}.Main
version: ${version}
api-version: "1.16"
depend:
  - Multiverse-Core
commands:
  AutoRespawnWorld:
    description: do something
    aliases: [ asw ]